# An exception will be raised
from math import *
exec("print(factorial(5))", {})
